### PR TITLE
define arithmetic on nucleotides and amino acids

### PR DESCRIPTION
**Pull request by bicycle1885**
This patch makes nucleotides and amino acids more like `Char`s. For example, `DNA_A + 1` is evaluated to `DNA_C` like `'a' + 1 == 'b'`. Total orders are defined, too. So now we can sort these symbols.

### CODE REVIEW

**Comment by bicycle1885** [comment]
Can anyone give me comments? I'd like to rebase #111 onto this patch.

**Comment by Ward9250** [comment]
It looks like a good idea to me. Changes look simple and painless too, and I don't know of anyway this interferes with other code in the modules. :shipit:

**Comment by Blahah** [comment]
What defines the ordering? It seems to me there is no natural (biological) ordering of the nucleotides. I think I'd like to see some explanation in comments of why this is necessary and useful, and how the ordering is chosen.

**Comment by Ward9250** [comment]
Good point, I didn't think about the ordering much, just that arithmetic ops on nucleotides is useful.

**Comment by bicycle1885** [comment]
There is no natural ordering, indeed. But without any ordering we cannot order DNA/RNA sequences, neither. A lexicographical order is implicitly assumed in many algorithms, for example, a suffix array is a sequence of indexes of sorted suffixes. Arbitrary ordering would work well as long as it is consistent among algorithms that use the order. The ordering I defined here is implied by the encoding of the nucleotides, which would be the most efficient and easiest way to keep consistency.

**Comment by Ward9250** [comment]
That does make sense if the ordering is consistent, but I suppose actually it's possible to have multiple ordering types and dispatch on those, which Is what I did for alignment anchors on my branch - you could order by their srcPos integer, or their alnPos integer. So if a different ordering in wanted or makes sense in another context it wouldn't be a huge problem.

**Comment by bicycle1885** [comment]
@Blahah Please merge this if you're fine :)

**Comment by bicycle1885** [comment]
I added comments in the code and arithmetic for Kmer. Please review it again :pray:

**Comment by Blahah** [comment]
Thanks! lgtm :shipit:

**Comment by Ward9250** [comment]
Still have my support! :shipit:

**Comment by bicycle1885** [comment]
Thank you!
Again, the CI failure on the nightly build is considered harmless.

**Pull request merged**
