### PR TITLE
Added the Dating submodule to Phylo.

### PR DESCRIPTION
**Pull request by Ward9250**
This PR adds a Dating submodule to Phylo. Initially it contains a simple procedure I designed for a larger software project on my PhD, which returns an estimation of the coalescence time between two sequences, based on assumptions formalised by modelling mutation accumulation between sequences as a binomial process.

### CODE REVIEW

**Comment by Ward9250** [comment]
This is ready for review. I can see test fail, something to do with failing when precompiling LightGraphs? This didn't happen when testing the Phylo module previously, so not sure what's going on there.

**Comment by vchuravy** [comment]
It would be nice to have docstrings for that function explaining what it does and also (if possible) give a reference.

**Comment by Ward9250** [comment]
Ok sure I can add those.

**Comment by Ward9250** [comment]
Added docstring, and also I now know the cause of the error, it's because a function in StatsBase, imported by LightGraphs no longer exists. This is being accounted for by LightGraphs, but won't change and fix the error until the next release.

**Comment by bicycle1885** [comment]
I can't see any tests related to this module. Did you forget to push them or something?

**Comment by Ward9250** [comment]
I just didn't add them yet whilst I chased up the LightGraphs.jl error business.

**Comment by Ward9250** [comment]
Ok I've added tests. If they pass I'd like to merge if no furthur objections.

**Comment by bicycle1885** [comment]
👍

**Pull request merged**
