### PR TITLE
add the Bio.IO.stream function

### PR DESCRIPTION
**Pull request by bicycle1885**
This implements the `Bio.IO.stream` function, which fixes a part of #288.

@kdmurray91, can you check if this solves the issue you mentioend?

### CODE REVIEW

**Comment by Ward9250** [comment]
:+1:

**Comment by Ward9250** [comment]
Do you find any benefit to @inline-ing the stream function? So as accessing the field just get's inlined into calling code?

**Comment by bicycle1885** [comment]
I guess no benefit because `stream` will not be called very often.

**Comment by kdmurray91** [comment]
@bicycle1885 Beautiful, I had an attempt to do this in the [parser refactor](https://github.com/BioJulia/Bio.jl/tree/parser-refactor) branch, and unsurprisingly yours works far better.

**Comment by bicycle1885** [comment]
@kdmurray91 Thank you :) I should have said you before starting my work.

I'm going to merge this if CI says okay.

**Pull request merged**
