### PR TITLE
Replace FactCheck with BaseTestNext

### PR DESCRIPTION
**Pull request by bicycle1885**
[BaseTestNext.jl](https://github.com/IainNZ/BaseTestNext.jl) is a testing package that will take over the `Base.Test` module on v0.5. This introduces `@testset` macro to group tests and prints pretty outputs. I believe this will be a standard way to write unit tests in the Julia community, so there is no reason to continue to use FactCheck.jl in Bio.jl.

I'd like to hear your opinions.

### CODE REVIEW

**Comment by Ward9250** [comment]
I say lets try it out on a branch and see how it does! I assume it can currently do all FactCheck.jl does :+1:

**Comment by bicycle1885** [comment]
This pull request is now ready to review. The major differences are:

* Use the BaseTestNext.jl package instead of FactCheck.jl
    * Use `@testset` instead of `facts` and `context`
    * Use `@test` and `@test_throws` instead of `@fact` and `@fact_throws`, respectively
* You can run tests by module.
    * You can pass test target name as a command-line argument to `test/runtests.jl` (e.g. `julia test/runtests.jl seq`)
    * Renamed some file names.

**Comment by bicycle1885** [comment]
The CI failure happened on all tested platforms (Linux, OS X, and Windows) on v0.5. I guess this is not directly related to the modification of this pull request, and may be related to (https://github.com/JuliaLang/julia/issues/14704). The following is the error message: 

```
banded: Error During Test
  Got an exception of type BoundsError outside of a @test
  BoundsError: attempt to access 3x7 Array{UInt8,2}:
   0xb0  0x33  0x02  0xd7  0x46  0x00  0x65
   0xd4  0x02  0x02  0x02  0x02  0x70  0x33
   0x00  0x01  0x01  0x01  0x08  0xd5  0x44
    at index [4,6]
   in setindex! at ./array.jl:305
   [inlined code] from /home/travis/.julia/v0.5/Bio/src/align/pairwise/algorithms/needleman_wunsch.jl:52
   in run! at /home/travis/.julia/v0.5/Bio/src/align/pairwise/algorithms/banded_needleman_wunsch.jl:216
   in run! at /home/travis/.julia/v0.5/Bio/src/align/pairwise/algorithms/banded_needleman_wunsch.jl:276
   in pairalign at /home/travis/.julia/v0.5/Bio/src/align/pairwise/pairalign.jl:86
   [inlined code] from /home/travis/.julia/v0.5/Bio/test/align/runtests.jl:546
   in anonymous at ./no file:4294967295
Test Summary:         | Pass  Error  Total
PairwiseAlignment     |  193      1    194
  SubstitutionMatrix  |   12            12
  AffineGapScoreModel |   21            21
  CostModel           |    9             9
  Alignment           |    6             6
  count_<ops>         |    5             5
  GlobalAlignment     |   53      1     54
    empty sequences   |    1             1
    complete match    |    3             3
    mismatch          |    6             6
    insertion         |   18            18
    deletion          |   21            21
    banded            |    4      1      5
  SemiGlobalAlignment |   12            12
  OverlapAlignment    |   15            15
  LocalAlignment      |   24            24
  EditDistance        |   22            22
  LevenshteinDistance |    2             2
  HammingDistance     |   12            12
ERROR: LoadError: LoadError: Some tests did not pass: 193 passed, 0 failed, 1 errored.
 in finish at ./test.jl:389
 [inlined code] from ./test.jl:563
 in anonymous at ./no file:4294967295
while loading /home/travis/.julia/v0.5/Bio/test/align/runtests.jl, in expression starting on line 286
while loading /home/travis/.julia/v0.5/Bio/test/runtests.jl, in expression starting on line 25
=================================[ ERROR: Bio ]=================================
```

**Comment by bicycle1885** [comment]
@Ward9250 BTW, are these messages intended, or just for debug purpose? 

```
...
DONE THE GET SPECIMENS!
DONE FUNCTION LOADING!
NOW ON Dict{Any,Any}("valid"=>true,"filename"=>"itemRgb.bed","origin"=>"kent")
NOW ON Dict{Any,Any}("valid"=>true,"filename"=>"bedPileUps-foo.bed","origin"=>"kent")
NOW ON Dict{Any,Any}("valid"=>true,"filename"=>"vgLoadMahoney-clonePcr.bed","origin"=>"kent")
NOW ON Dict{Any,Any}("valid"=>true,"filename"=>"overlapSelect-NM_001206.bed","origin"=>"kent")
NOW ON Dict{Any,Any}("valid"=>true,"filename"=>"overlapSelect-NM_015110.bed","origin"=>"kent")
NOW ON Dict{Any,Any}("valid"=>true,"filename"=>"overlapSelect-NM_015110.split.bed","origin"=>"kent")
NOW ON Dict{Any,Any}("valid"=>true,"filename"=>"overlapSelect-ceil1.in.bed","origin"=>"kent")
NOW ON Dict{Any,Any}("valid"=>true,"filename"=>"overlapSelect-ceil1.sel.bed","origin"=>"kent")
NOW ON Dict{Any,Any}("valid"=>true,"filename"=>"overlapSelect-mrna.bed","origin"=>"kent")
NOW ON Dict{Any,Any}("valid"=>true,"filename"=>"overlapSelect-refgene.bed","origin"=>"kent")
NOW ON Dict{Any,Any}("valid"=>true,"filename"=>"overlapSelect-statsSelect.bed","origin"=>"kent")
NOW ON Dict{Any,Any}("valid"=>false,"filename"=>"overlapSelect-wideIn.bed","origin"=>"kent")
NOW ON Dict{Any,Any}("valid"=>true,"filename"=>"overlapSelect-wideSelect.bed","origin"=>"kent")
...
```

**Comment by Ward9250** [comment]
I'm not sure, I think they are related to BED, which I didn't implement. You'd have to ask @dcjones

**Comment by bicycle1885** [comment]
@Ward9250 But `git blame` says you inserted these `println`s in this commit:
https://github.com/BioJulia/Bio.jl/commit/817b1c2b2193ee13c13df98bc363234e39c96a52 (see test/intervals/TestIntervals.jl).

**Comment by Ward9250** [comment]
Oh just checked the commit, I do remember putting in `println("DONE THE GET SPECIMENS!")`, `println("DONE FUNCTION LOADING!")`, `println("NOW ON $specimen")`. Yes that was so I could see why the testing of Interval stuff failed when I was working on SlidingWindows.

**Comment by bicycle1885** [comment]
OK, so I'm going to remove these printings.

**Comment by Ward9250** [comment]
So I'm happy for this to merge, :shipit: providing the CI error is some upstream Julia issuer another issue not directly related to this PR. From the output it looks like it might be due to some set index call to an array. And that occurs in testing banded alignments. Do you think this a Julia issue or is there some code in alignments that tries to index an array incorrectly?

**Comment by bicycle1885** [comment]
I think this is related to the Julia issue I mentioned above because (1) the test failure doesn't happen on v0.4 on all platforms, and (2) the only difference is the Julia compiler (v0.4 vs. v0.5).

**Comment by Ward9250** [comment]
Ok, just waiting on a second review then. I'll make sure to use this framework for Phylo tests and replace what is there.

**Comment by bicycle1885** [comment]
The problem has been fixed by the upstream (https://github.com/JuliaLang/julia/pull/14830) (I checked on my machine) and now we can merge this one.

**Comment by Blahah** [comment]
Sorry it took me a long time to get around to this - it's actually a very straightforward PR. Thanks @bicycle1885 for moving everything over to the new setup (almost seems pointless given how similar they are, but it does make sense to keep current with the Julia community).

LGTM! :shipit:

**Pull request merged**
