### PR TITLE
Modify Interval constructors.

### PR DESCRIPTION
**Pull request by bicycle1885**
Small tweaks. Now we can write `Interval` like the former below:

```julia
Interval("chr1", 10, 20, '+')
Interval("chr1", 10, 20, STRAND_POS)
```

Also, I added the `strand` accessor like `first` and `last`.

One thing I want to add is a sequence name accessor.  `seqname` or just `name`?

### CODE REVIEW

**Comment by bicycle1885** [comment]
I'd like to merge this small patch today if no objections.

**Comment by Blahah** [comment]
Looks good to me. In the context of an interval, `name` suggests the name of the interval itself, while `seqname` unambiguously refers to the reference sequence name.

**Comment by bicycle1885** [comment]
Thanks. I added `seqname`, too.

**Comment by Ward9250** [comment]
:shipit:

**Comment by Blahah** [comment]
:shipit:

**Pull request merged**
