### PR TITLE
Approximate search/rsearch for sequences.

### PR DESCRIPTION
**Pull request by bicycle1885**
This is the second search tool I mentioned in #152. This allows approximate sequence searching up to `k` errors with an bit-parallel algorithm.

### CODE REVIEW

**Comment by bicycle1885** [comment]
This is ready to review.

**Comment by bicycle1885** [comment]
Any comments? I think this is ready to merge.

**Comment by Ward9250** [comment]
I'll try and read this today, but it might not be until the evening.

**Comment by Ward9250** [comment]
:+1: LGTM buddy! :)

**Comment by bicycle1885** [comment]
Thanks :)

**Pull request merged**
