### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by prcastro**
Fix type leading to a travis failure

### CODE REVIEW

**Comment by prcastro** [comment]
I also believe IntervalTrees should tag a new version, so we have access to features like `Intersection`.

**Comment by Ward9250** [comment]
I'm happy to merge this to fix the typo. I would make an issue on the BioJulia/IntervalTrees repo to flag the version tag issue to DC Jones - I do not remember if his IntervalTrees repo is more advanced than the one under BioJulia/

**Comment by Ward9250** [comment]
Is branch ok to go? Or is more work to come on it?

**Comment by dcjones** [comment]
I'll tag a new IntervalTrees today. I wanted to try to work out [an issue](https://github.com/BioJulia/Bio.jl/blob/master/src/intervals/intervalcollection.jl#L233) first.

**Comment by Ward9250** [comment]
Thanks @dcjones, I notice this will fix where TravisCI builds are failing, build 327.2 citing the error:

ERROR: LoadError: LoadError: LoadError: LoadError: LoadError: UndefVarError: Intersection not defined

**Comment by dcjones** [comment]
Ok, tests are green on 0.4 now.

**Comment by Ward9250** [comment]
Awesome! :+1:

**Comment by prcastro** [comment]
Do you know why 0.3 fails? Is it fixable? If not, why don't we get rid of 0.3 tests on travis?

**Comment by Ward9250** [comment]
Personally I have been writing and running code on whatever the current commit to Julia is that day. So I'm happy to only have 0.4. I want to hear what the majority vote is before removing 0.3 though.

**Pull request merged**
