### PR TITLE
[RTR] Separate ragel from julia source

### PR DESCRIPTION
**Pull request by kdmurray91**
Addresses #166

### CODE REVIEW

**Comment by kdmurray91** [comment]
Hi all, this is ready to review. I'm not a member of the biojulia org, so I can't set labels.

**Comment by kdmurray91** [comment]
BigBed is essentially already split. I could rename `bigbeddata` to `bigbed-parser` for consistency if you think that's a good idea.

**Comment by bicycle1885** [comment]
It sounds reasonable to rename the BigBED parser file 👍

**Comment by bicycle1885** [comment]
LGTM :shipit:

**Comment by Ward9250** [comment]
:shipit:

**Comment by bicycle1885** [comment]
Thank you, @kdmurray91 !

**Pull request merged**
