### PR TITLE
Writing of FASTQ sequences

### PR DESCRIPTION
**Pull request by kdmurray91**
NB: this is work in progress

Hi all,

As discussed on gitter, I've implemented a function to write a FASTQ record to an IO stream. I imagine that it could be implemented better, including using some functionality from `quality.jl` to do the quality string conversion.

Also, I'd assume a FASTA writer would come in handy.

Let me know what you think! I'm still not very experienced w/ Julia, so any and all criticism is welcome :)

Cheers,
Kevin

### CODE REVIEW

**Comment by kdmurray91** [comment]
(pasting in from gitter, as I'm not sure @dcjones saw the comment)

> @dcjones I'm not sure, but I think I may have found a bug in `quality.jl`, with respect to Illumina 1.5-1.8 quality scores. By my reading of [wikipedia](https://en.wikipedia.org/wiki/FASTQ_format#Encoding), the range of the Illumina 1.5 pipline values is 3-40. Which with the offset of 64, is the ASCII range `CDE...fgh` (typically, full range goes to 62 and  `~`). So, should [the Illumina 1.5 quality config](https://github.com/BioJulia/Bio.jl/blob/2ae3aab1f383a36579edc12820e9fe0984783264/src/seq/quality.jl#L62) be `['C', '~',  3]`? Or perhaps `['B', '~', 2]`?

**Comment by dcjones** [comment]
Sorry to let this collect dust. I think it looks good. There are a few minor syntax updates needed that I can do (`@doc` is no longer needed for docstrings, and factcheck uses `-->` instead of `=>` now).

I think you're right that Illumina 1.5 is not correct, but it seems like it should be `['B', '~', 2]`, since `B` can occur even though it has some special meaning. Sound right?

**Comment by kdmurray91** [comment]
@dcjones that sounds right, yeah. I've rebased onto current master and will fix the factcheck issues.

**Comment by kdmurray91** [comment]
And the Illumina 1.5 issue too.

**Comment by kdmurray91** [comment]
@dcjones I think all your comments have all been addressed.

**Comment by dcjones** [comment]
Thanks!

**Pull request merged**
