### PR TITLE
fix BigBed parser

### LINKED ISSUE #159: BigBed Tests Fail
The final two tests in the Intervals module fail.

```
BED → BigBed → BED round-trip: Error During Test
  Got an exception of type ArgumentError outside of a @test
  ArgumentError: ensureroom failed, IOBuffer is not writeable
   in ensureroom at ./iobuffer.jl:175
   in write at ./iobuffer.jl:319
   in write at io.jl:54
   in write at /home/travis/.julia/v0.4/Bio/src/intervals/bigbed.jl:300
   in bigbed_write_index at /home/travis/.julia/v0.4/Bio/src/intervals/bigbed.jl:1443
   in write_bigbed_bigwig at /home/travis/.julia/v0.4/Bio/src/intervals/bigbed.jl:1811
   in write at /home/travis/.julia/v0.4/Bio/src/intervals/bigbed.jl:1725
   [inlined code] from /home/travis/.julia/v0.4/Bio/test/intervals/runtests.jl:460
   in anonymous at no file:0
   in include at ./boot.jl:261
   in include_from_node1 at ./loading.jl:320
   [inlined code] from /home/travis/.julia/v0.4/Bio/test/runtests.jl:27
   in anonymous at no file:0
   in include at ./boot.jl:261
   in include_from_node1 at ./loading.jl:320
   in process_options at ./client.jl:280
   in _start at ./client.jl:378
BigBed Intersection: Error During Test
  Got an exception of type ArgumentError outside of a @test
  ArgumentError: ensureroom failed, IOBuffer is not writeable
   in ensureroom at ./iobuffer.jl:175
   in write_sub at ./iobuffer.jl:299
   in write at ./iobuffer.jl:316
   in writebytes at /home/travis/.julia/v0.4/BufferedStreams/src/sources.jl:154
   in writebytes at /home/travis/.julia/v0.4/BufferedStreams/src/sources.jl:9
   in flushbuffer! at /home/travis/.julia/v0.4/BufferedStreams/src/bufferedoutputstream.jl:39
   in close at /home/travis/.julia/v0.4/BufferedStreams/src/bufferedoutputstream.jl:121
   in writebytes at /home/travis/.julia/v0.4/Libz/src/sink.jl:144
   in flushbuffer! at /home/travis/.julia/v0.4/BufferedStreams/src/bufferedoutputstream.jl:39
   in close at /home/travis/.julia/v0.4/BufferedStreams/src/bufferedoutputstream.jl:121
   in bigbed_write_blocks at /home/travis/.julia/v0.4/Bio/src/intervals/bigbed.jl:1044
   in write_bigbed_bigwig at /home/travis/.julia/v0.4/Bio/src/intervals/bigbed.jl:1800
   in write at /home/travis/.julia/v0.4/Bio/src/intervals/bigbed.jl:1725
   [inlined code] from /home/travis/.julia/v0.4/Bio/test/intervals/runtests.jl:481
   in anonymous at no file:0
   in include at ./boot.jl:261
   in include_from_node1 at ./loading.jl:320
   [inlined code] from /home/travis/.julia/v0.4/Bio/test/runtests.jl:27
   in anonymous at no file:0
   in include at ./boot.jl:261
   in include_from_node1 at ./loading.jl:320
   in process_options at ./client.jl:280
   in _start at ./client.jl:378
```

### PR DESCRIPTION
**Pull request by bicycle1885**
This will fix #159 after https://github.com/BioJulia/BufferedStreams.jl/pull/11 and https://github.com/BioJulia/Libz.jl/pull/21. So, we need to tag and release new versions of BufferedStreams.jl and Libz.jl to make TravisCI happy.

### CODE REVIEW

**Comment by bicycle1885** [comment]
The tests of Julia 0.4 passed on Linux and OS X. But on OS X, the process was terminated by an unknown reason (the message says: "No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.").

**Comment by Ward9250** [comment]
Is it when something is pulled from the web?

**Comment by bicycle1885** [comment]
Maybe. It seems to be during building the documents: https://travis-ci.org/BioJulia/Bio.jl/jobs/128082160. The last output is: "Documenter: skipping docs deployment."

**Comment by Ward9250** [comment]
The Documenter: skipping docs deployment is because docs are only ever deployed upon pushed to the master branch. This is the set behaviour for all PRs and branches that aren't aster, and shouldn't result in a travis failure.

**Comment by bicycle1885** [comment]
I see. Let's merge this branch though I don't have any clue to resolve the Travis failure problem on OS X. If this is reproducible, we can open an issue for that.

**Comment by Ward9250** [comment]
:+1: This sounds like a good plan!

**Pull request merged**
