### PR TITLE
[WIP] Bumping the test coverage

### PR DESCRIPTION
**Pull request by kdmurray91**
This PR implements a few new tests and miscellaneous refactors. I find writing unit tests gets me familiar with a codebase in a vaguely productive way. 

Cheers,
K

### CODE REVIEW

**Comment by kdmurray91** [comment]
P.S. I intend to rebase as I go to keep commits atomic, and might force-push to this branch along this way. Fair warning.

**Comment by Ward9250** [comment]
For clarification, force push to kdmurray:testcov??

**Comment by kdmurray91** [comment]
Yeah, of course. I'd never force push to a shared repo

**Comment by bicycle1885** [comment]
I've made the master branch [protected](https://help.github.com/articles/defining-the-mergeability-of-pull-requests/) just now so that nobody can do force-pushes to it.

**Comment by kdmurray91** [comment]
@bicycle1885 Thanks!

**Pull request closed without merging**
