### PR TITLE
open with a do block

### PR DESCRIPTION
**Pull request by tkelman**
so the file handle gets closed and the file can be cleaned up on Windows

### CODE REVIEW

**Comment by kdmurray91** [comment]
:+1: LGTM, will leave to others to hit merge.

**Comment by bicycle1885** [comment]
Great! Thank you @tkelman 👍

**Comment by tkelman** [comment]
No problem. Fun tip, when a PR changes mostly whitespace like this one, append `?w=1` to the end of the `/files` url and you get a much shorter diff: https://github.com/BioJulia/Bio.jl/pull/252/files?w=1

**Comment by bicycle1885** [comment]
GitHub should put that button on the diff page.

**Pull request merged**
