### PR TITLE
New doc syntax

### PR DESCRIPTION
**Pull request by prcastro**
Addressing #60

### CODE REVIEW

**Comment by prcastro** [comment]
I can't figure Travis' error out. Does any know what is happening?

**Comment by kescobo** [comment]
Related: current [CONTRIBUTING.md](https://github.com/BioJulia/Bio.jl/blob/master/CONTRIBUTING.md) says:

>Types and functions must be documented using Docile style docstrings.

Should be updated no?

**Comment by prcastro** [comment]
If I'm not mistanken, this PR already updates this.

**Comment by Ward9250** [comment]
The error on the nightlies builds? I'm not sure - I use and test Bio.jl using bleeding edge and don't usually have any problems. I haven't looked at the travis logs, I'll have a look later today if I get chance.

**Comment by prcastro** [comment]
All green now

**Comment by dcjones** [comment]
Looks good. Could you change the julia version in REQUIRE to `julia 0.4-`?

**Comment by Ward9250** [comment]
Yep I agree this looks good =] just have REQUIRE specify 0.4 and one of us will make the merge.

**Comment by bicycle1885** [comment]
If the new docstring style does nothing harmful, is v0.4 requirement needed?

**Comment by prcastro** [comment]
Somehow it is harmful, since we wuld deliver an undocumented for v0.3 users without tis requirement.

**Pull request merged**
