### PR TITLE
Composition

### PR DESCRIPTION
**Pull request by bicycle1885**
This unifies `Composition` and `KmerCounts` into `Composition` and deprecates `KmerCounts`. I also added the `merge` method for `Composition` to accumulate statistics of multiple sequences.

### CODE REVIEW

**Comment by Ward9250** [comment]
:+1: LGTM - as a heads up my internet is being sketchy and I might not be able to get on here over the next few days until it is resolved.

**Comment by bicycle1885** [comment]
Okay, so please check this pull request when you have time.

**Comment by Ward9250** [comment]
I've just read through the changes, this looks absolutely fantastic, and pre-empts me having to implement nucleotide composition for my distance calculation methods. Brilliant stuff! :shipit:

**Comment by bicycle1885** [comment]
Thank you 😄

**Pull request merged**
