### PR TITLE
Added editorconfig file

### PR DESCRIPTION
**Pull request by Ward9250**
Written an .editorconfig as suggested in #87

### CODE REVIEW

**Comment by prcastro** [comment]
Bio.Align introduces some C code to the table. It would be nice to see it already in editorconfig.

**Comment by dcjones** [comment]
Could you change the pattern to `*.{rl,jl}` to include our julia-hosted ragel files? I don't think @Ward9250  meant to include those SeqAn C++ files in #36, so adding C/C++ probably isn't necessary.

**Comment by Ward9250** [comment]
Correct, the C/C++ files are not going to be part of Align, I did put them in, but they are there only for reference whilst I work on Align, A). For me, and B). For others so they can see the basis of what I've done, and where I've altered the design based on our needs.

**Comment by prcastro** [comment]
Just remove WIP tag when you're ready to merge this PR

**Comment by Ward9250** [comment]
Ok cool, WIP removed, two people say yep and it goes in. The WIP tag is used by Waffle, so maybe we should use some other tag to signal a "I'm done with this, please review" tag.

**Comment by prcastro** [comment]
RTR (Ready to Review)?

**Comment by Ward9250** [comment]
Sounds good!

**Comment by Blahah** [comment]
All looks good - merged

**Pull request merged**
