### PR TITLE
Added 26 tests for Nucleotide Sequences

### PR DESCRIPTION
**Pull request by brk00**
Added tests for sequence length, sequence access (iterations and out of bounds access), creation of empty sequences and creation of subsequence from ranges.

I hope the coverage goes up a little bit with this PR.

### CODE REVIEW

**Comment by brk00** [comment]
Doesn't Coveralls track the PRs on this repo?

**Comment by dcjones** [comment]
Nice work. We should get coverage, but there are currently some issues with dependencies of the coverage package on julia 0.4 nightlies (https://github.com/jakebolewski/JuliaParser.jl/issues/18). I guess we could change our travis config to get coverage data from julia 0.3.

**Comment by brk00** [comment]
I believe we should change travis config to get coverage data from julia 0.3 util 0.4 is out.

**Comment by dcjones** [comment]
Ok, let's merge this (I don't think anyone would object to more tests) then see if we can get coverage working.

**Comment by dcjones** [comment]
Ok, we have coverage data once again!
https://coveralls.io/r/BioJulia/Bio.jl

**Comment by brk00** [comment]
Very nice, coverage is up as expected. I'll try to improve coverage even more later this week. I expect getting something like ~80% for all Seq files (nucleotides, aminoacids and geneticcodes).

**Pull request merged**
