### PR TITLE
Decompose Bio.Structure

### PR DESCRIPTION
**Pull request by jgreener64**
Once the BioStructures.jl package (https://github.com/BioJulia/BioStructures.jl) is tagged and released this removes the code from Bio.jl.

### CODE REVIEW

**Comment by Ward9250** [comment]
This looks ok to me at first glance, but we should perhaps wait for BioStructures release, so as then the CI can actually run with the BioStructures dependency available, just to be safe.

**Comment by jgreener64** [comment]
Yes agreed.

**Comment by jgreener64** [comment]
So having re-triggered the build it fails because there are no tagged versions of BioStructures.jl for Julia v0.5. The first release is tagged for v0.6 minimum.

So I guess this PR should wait until Bio.jl is ready to transfer to Julia v0.6 generally?

**Comment by Ward9250** [comment]
Well since all the old syntax actually works with 0.6 - just a few warnings here and there, we can try and just bump up the CI to 0.6, change the bare minimum syntax, and continue with the decompose :+1:

**Comment by jgreener64** [comment]
Sounds good. I see you've started this process, thanks.

**Comment by Ward9250** [comment]
Ok I've resolved the merge commits, now we can see how the tests go this time, there should be no issues.

**Comment by Ward9250** [comment]
Ok this can merge now, thanks for all the hard work @jgreener64, fantastic stuff!

**Comment by jgreener64** [comment]
Great, thanks for the merge @Ward9250 .

**Pull request merged**
