### PR TITLE
Update travis

### PR DESCRIPTION
**Pull request by Ward9250**
Seeing if I can get travis to use their new infrastructure they keep reminding us of

### CODE REVIEW

**Comment by dcjones** [comment]
Looks good. You have two extraneous merge commits in this PR though. Can you fix that?

**Comment by Ward9250** [comment]
Yeah this bugs me, I hit the update from master button in the Github app, which I guess probably doesn't do a proper rebase. I'll see, but I'm cautious about rebasing and reseting because of horror stories of people well and truly screwing it up.

**Comment by dcjones** [comment]
I haven't used the Github app, but this is the kind of thing you can fix `git rebase -i` and deleting the extraneous commits. But that's dangerous stuff, so backup the branch first if you try it. :cold_sweat:

**Comment by dcjones** [comment]
Cool, you got it.

**Comment by Ward9250** [comment]
Ok I think this is sorted. I went to my Fork's master. Did a hard reset to before those two merge commits from BioJulia/master to Ward9250/master. Then neatly rebased Ward9250/master on BioJulia/master. Then again did hard reset on this PR, rebased, and then cherry-picked the one commit that actually applies to this.

**Comment by dcjones** [comment]
Git can be so exciting sometimes.

**Pull request merged**
