### PR TITLE
FASTA Index

### LINKED ISSUE #177: .fai (FASTA index) support
(memorandum)

Supporting the .fai file format would be useful to index large a FASTA file and load arbitrary sequences from it. The format is easy to parse (http://www.htslib.org/doc/faidx.html) but seeking a file with `Base.seek` requires some modifications of BufferedStreams.jl and the FASTA parser.

### PR DESCRIPTION
**Pull request by bicycle1885**
This will close #177.

### CODE REVIEW

**Comment by bicycle1885** [comment]
Now ready to merge 😃

**Comment by Ward9250** [comment]
:+1:

**Comment by Ward9250** [comment]
Maybe an entry in the manual, but happy if that goes in here or in another PR, depends what you'd like to do :)

**Comment by bicycle1885** [comment]
I will write docs along with 2bit file format soon.

**Pull request merged**
