### PR TITLE
Precompile

### PR DESCRIPTION
**Pull request by bicycle1885**
I'm try to precompile Bio.jl module locally. Precompiling greatly cut down the load time especially for parsers.

**startup.jl**
```julia
println("--- loading ---")
tic()
using Bio.Seq
using Bio.Align
using Bio.Intervals
using Bio.Structure
toc()

println("--- running ---")
tic()
for rec in open("sample.bed", BED) end
for rec in open("sample.fasta", FASTA) end
for rec in open("sample.fastq", FASTQ) end
toc()
```

**Not precompiled (master)**
```
~/.j/v/Bio ((eeece67...)|…) $ julia startup.jl
--- loading ---
elapsed time: 7.950095168 seconds
--- running ---
elapsed time: 9.586036993 seconds
```

**Precompiled**
```
~/.j/v/Bio (precompile|…) $ julia startup.jl
--- loading ---
elapsed time: 1.373317087 seconds
--- running ---
elapsed time: 5.049919548 seconds
```

I guess there is still more room to improve it by aggressively precompiling functions. To do that, we need to benchmark the precompiling phase but currently it requires a patched Julia compiler and [SnoopCompile.jl](https://github.com/timholy/SnoopCompile.jl), which I've not tried yet.

### CODE REVIEW

**Comment by vchuravy** [comment]
Parts of #179 are in here., I guess that was accidental?

**Comment by bicycle1885** [comment]
It is because I've forked this branch from `bicycle1885:fasta-type`. I will merge #179 sooner or later so I directly forked from it to avoid rebasing.

**Comment by vchuravy** [comment]
Makes reviewing a bit harder :) The precompile code looks good to me.

**Comment by bicycle1885** [comment]
Okay, I will merge this soon since this won't break anyting.

**Comment by kdmurray91** [comment]
Oooh yes please. This will definitely be helpful here. I assume we can lazily add to precompile.jl as ww find more things that would benefit from precompilation?

Actually, is it possible for external libraries to call precompile on Bio.jl's code? I.e. could I extended the required precompile calls in precompile.jl in a library that uses Bio.jl?

**Comment by Ward9250** [comment]
I likes the looks of this!

**Pull request merged**
