### PR TITLE
Incoroprate an FOSGAA global alignment

### PR DESCRIPTION
**Pull request by BenJWard**
So we've had the BioJulia/fogsaa repo for a while, which just works on strings and implements a fast B&B global alignment algorithm, and with recently using Bio.Align pairwise global alignments in my scripts I was impressed, although speed was not the quickest - given I was aligning very large contigs of a FALCON assembly. So I thought hey why not get fogsaa incorporated as an option in the global pairalign.

There are three steps I currently identify, I've already made a commit doing a bit of step 1:
- [ ] Go through code, make variable names more meaningful, refactor any pieces that could be more simply expressed, and make sure it's julian, and add comments for the lay reader to understand what the algorithm does.
- [ ] Refactor code so it is of the form currently used in Bio.Align pairwise: There should be a FOGSAA type just as there is a NeedlemanWunsch type and so on, that stores data. The alignment algorithm should then be factored so as it fits with the current framework i.e. there is a run method for the algorithm type and so on.
- [ ] A further refactor of the code so as it works not just with strings but all our sequence types, and makes use of Anchors and Operations and Trace, instead of defining its own, which is what it currently does.

### CODE REVIEW

**Comment by bicycle1885** [comment]
I worry the code you based on is not distributed under any OSS license, so I think we need to write it from scratch.

**Comment by Ward9250** [comment]
The code I'm using is from BioJulia/fogsaa which is a fork of kjenova/fogsaa, there's no license assigned to it. Other than a reference to the nature paper they do not state where it comes from, I assumed they wrote it themselves based on a reading of the nature paper.

**Comment by bicycle1885** [comment]
If so, the original author holds all rights and we cannot redistribute it without their permission.

**Comment by Ward9250** [comment]
I've just done some digging, and the original FOGSAA is a C++ program which also, like the julia version of FOGSAA is available for download, and as in all science, you are told to download and check out the source code and it is freely available. However, here again, there is not license, and so technically all rights are reserved, and since downloading implicitly means making a copy, it's a grey area as to whether or not a scientist is even allowed to download, compile, and use the software, even though it has been published in Nature, with the intent of it being used! Therefore I feel the lack of license has been an oversight on behalf of the authors. I will chase this up and report back.

**Comment by Ward9250** [comment]
Ok I've sent an email to @kjenova

**Comment by Ward9250** [comment]
A license was added which differs only from the MIT in that there is no copyright. I also have an email from kjenova with express permission for us to use the fogsaa repo. :+1:

**Comment by BenJWard** [comment]
This should be moved to BioAlignments.jl

**Pull request closed without merging**
