### PR TITLE
One-hot encoding of nucleotides.

### PR DESCRIPTION
**Pull request by bicycle1885**
This is an implementation of #244.

Still work-in-progress quality, but, I think, the earlier, the better.

- [x] Pass all tests.
- [x] Clean up code.
- [x] Check performance regression.

### CODE REVIEW

**Comment by bicycle1885** [comment]
I may need to add more metrics, but the performance looks pretty good:
benchmarks_4

**Comment by bicycle1885** [comment]
benchmarks_5

**Comment by bicycle1885** [comment]
Now this is ready to review and merge.

Change highlights:
* `DNANucleotide` and `RNANucleotide` are encoded in one-hot encoding.
* Changed order of nucleotides (e.g. `DNA_Gap` is now less than `DNA_A`).
* Deprecated `SymbolRange` bacause it has confusing behaviors for nucleotides.
* Export `ACGT` and `ACGU`, which work like `DNA_A:DNA_T` and `RNA_A:RNA_U`, respectively.

**Comment by Ward9250** [comment]
LGTM mate! :)

**Comment by bicycle1885** [comment]
Thanks, @Ward9250. I'm going to merge this soon.

**Pull request merged**
