### PR TITLE
Remove Compat dependence

### PR DESCRIPTION
**Pull request by prcastro**
We require Julia v0.4, therefore there's no need to use Compat.

### CODE REVIEW

**Comment by bicycle1885** [comment]
Great! This is what I wanted to do for a while.
But one problem would be this will conflict with many other pull requests.
So, I think merging this should be delayed and should be done after merging some large pull requests.

**Comment by bicycle1885** [comment]
Also it would be better to rename `String` to `AbstractString`: the former is no longer used in the standard library.

**Comment by prcastro** [comment]
The only conflicting PR I can see is #37. Other PRs aren't affect AFAIK. @dcjones , do you mind merging this PR and rebasing #37? I usually mess things up when solving merge conflicts on Git.

**Comment by dcjones** [comment]
I think #37 wouldn't be too bad, but #85 worries me a little since it modifies a lot of files.

**Comment by prcastro** [comment]
Oh, you're right. Maybe we will have to wait until both of them are merged.

**Comment by dcjones** [comment]
@prcastro You're free to rebase this when you have a chance.

**Comment by prcastro** [comment]
Superseded by #97

**Pull request closed without merging**
