### PR TITLE
RFC: [Seq] Code refactor and bug solving

### PR DESCRIPTION
**Pull request by brk00**
Here is a list of what I did:

* Split the code in several files (#28)
* Changed many function definitions to one-liners
* `nucleotide_count` was changed to the contructor `NucleotideCounts`
* Implemented (badly) a `NucleotideCounts` method for K-mers (+ Tests)
* Solved  bugs (including ones with constructors, string decorators)
* Simplified nucleotide's `show()`
* Changed print formatting of sequences
* Improved commenting

### CODE REVIEW

**Comment by brk00** [comment]
Any specific problem holding this from being merged?

**Comment by Blahah** [comment]
@brk00 just that it needs review by two more people first

**Comment by dcjones** [comment]
I went ahead and pulled trigger. No point in letting this languish for months when it has some clear improvements.

@brk00 We'll try to get faster with this in the future, hopefully you're not totally put off from contributing again. :bouquet:

**Comment by Ward9250** [comment]
Gah! Apologies @brk00 - If I had known this was still open and waiting I would have reviewed it for you, I thought it was already done.

**Pull request merged**
