### PR TITLE
Setting up Lapidary.jl to generate BioJulia documentation.

### PR DESCRIPTION
**Pull request by Ward9250**
With the updates to BioSequence and the oncoming merge of the newest branch #135, so should come updated documentation and tutorials to ensure users are not left confused. Judo.jl is no longer supported and so this branch and PR is to see what we can do with Lapidary.jl.

### CODE REVIEW

**Comment by bicycle1885** [comment]
Thank you! Is that possible to host docs as a webpage?
DataFrames.jl is doing a similar thing: https://github.com/JuliaStats/DataFrames.jl/pull/929

**Comment by Ward9250** [comment]
It is possible! :) There is even integration with travis and mkdocs and
gh-pages. I'm working through the tutorial and stages to get that working
today. What's lovely about Lapidary.jl, and what swung me in it's favour is
that the examples act like tests, so you know the documentation and
examples are up to date and compatible with the current codebase!

**Comment by bicycle1885** [comment]
Great! Let's finish this migration before merging #135. Then, I'll rebase #135 on it and fix docs about sequences.

**Comment by Ward9250** [comment]
I'd like to merge this and see if it works.

**Comment by bicycle1885** [comment]
Awesome! Looks beautiful!

Adding `codehilite` to `markdown_extensions` (https://github.com/MichaelHatherly/Lapidary.jl/blob/master/docs/mkdocs.yml#L17) may enable syntax highlighting.

**Comment by Ward9250** [comment]
I just added the extension, hopefully it's active now.

**Comment by Ward9250** [comment]
I'll love to edit the CSS a bit and use one that is a bit more in with the branding, but at least for now it works, and is ready for people to write the contents of docs with, and it will just be updated and hosted by magic.

**Comment by jgreener64** [comment]
This is really cool. I'll get writing the `Bio.Structure` docs in this format.

**Comment by bicycle1885** [comment]
Please! Go ahead.

**Comment by Ward9250** [comment]
Cool, I'm still mucking about on master a little bit but nothing fundamental, just trying to get the Bio.jl logo to appear in docs and doing tweaks and stuff. Nothing that stops anybody rebasing on master and writing their docs.

**Comment by Ward9250** [comment]
Ok now the system works, I'm going to stop committing directly to master. Further documentation additions and changes should be in PRs like other contributions - it's just committing to master directly was required to force changes to force the builds in order to get it up and running and tested.

**Pull request merged**
