### PR TITLE
Mutation Counting & Distance API redux

### PR DESCRIPTION
**Pull request by Ward9250**
Doing the work increasing the performance of mutation counting in DNA, and RNA sequences, I realised I really did not like the API/interface for mutation counting and Distance computation. This sorts the horrid stuff out and makes the API consistent, as well as adding more site/mutation types that can be counted.

### CODE REVIEW

**Comment by jgreener64** [comment]
Minor: by 'naieve' do you mean 'naive'?

**Comment by Ward9250** [comment]
I do indeed!
I'll fix that shortly.

**Comment by Ward9250** [comment]
I'm going to try and do a big squash and merge this very soon, as it works as I intend it to, polishing and adjustment of the distance computations will then follow in a set of smaller PRs.

**Comment by Ward9250** [comment]
Tests pass, except on mac but it seems to be an issue with building HDF5, unrelated to this PR. I'll merge at 4:00pm if there are not further comments.

**Pull request merged**
