### PR TITLE
replace sequence types with BioSequence

### PR DESCRIPTION
**Pull request by bicycle1885**
This pull request introduces a new sequence type: `BioSequence{A<:Alphabet}`. The main purpose of this is to store more various nucleotides in a sequence (see #122 for discussion). The `BioSequence` type is indexed by a subtype of `Alphabet`, which indicates the domain (or set) of biological characters. For example, the old `DNASequence` is now `BioSequence{DNAAlphabet{4}}` (here `DNAAalphabet{4}` is a subtype of `Alphabet` and its type parameter, `4`, indicates the number of encoding bits). At the moment, this pull request is really premature and the tasks below should be done before merge.

- [x] Finish implementation of `BioSequence`.
  - [x] Basic operations
  - [x] Parsers
- [x] Pass tests.
- [x] Add more ambiguous nucleotides (#122) and stop codon (#134).
- [x] Check performance regression.

---
EDIT 2016-03-06

- [x] Add tests.

### CODE REVIEW

**Comment by bicycle1885** [comment]
I'm wondering whether `seq[i:j]` and `sub(seq, i:i)` should return a view or copy. The current master branch makes a view for immutable sequences and a copy for mutable sequences, but people may expect `sub` to return a view even for mutable sequences like vectors.

**master**

| mutability | `seq[i:j]` | `sub(seq, i:j)` |
|---|---|---|
| immutable | view | view |
| mutable | copy | copy |

**my suggestion**

| mutability | `seq[i:j]` | `sub(seq, i:j)` |
|---|---|---|
| immutable | view | view |
| mutable | copy | view |

**Comment by Ward9250** [comment]
I think there may be a case to change this, to have sub return a view even
of a mutable sequence. But only if we are clear that, because the user is
calling sub, they are explicitly asking for a view, and if it's a view of a
mutable sequence - well that's their lookout, they should expect changes
may affect things. However, if you use the indexing operation, if the
sequence is immutable, you can safely make the efficiency gains made
possible by using a view instead of an actual copied subset.

**Comment by Ward9250** [comment]
This is great! I've had to spend yesterday and today working on thesis chapter, but over the weekend I will do some work on this and phylo.

**Comment by Ward9250** [comment]
I've been looking at what you've done with Alphabet, and have just about worked out the idea for a macro, which allows people to create new alphabets for BioSequence, without having to code all the code for the type, with all the bitsof's and so on.

**Comment by bicycle1885** [comment]
Cool. It's almost finished to pass tests except a failing one and ones that touch internals I've changed. When all tests passed, I'll squash all commits into one and start to work on ambiguous nucleotides and performance problems.

**Comment by bicycle1885** [comment]
All tests have passed (with minimal fix)! Now I'm going to work on adding more nucleotides.

**Comment by Ward9250** [comment]
Wohooo! I've nearly finished the alphabet builder macro too. Just a few
more tweaks and it will be done tonight.

**Comment by bicycle1885** [comment]
I made a simple benchmark script to check the regression of this branch vs. master: https://gist.github.com/bicycle1885/cf8a09e2bf0f21d563b9.

And the following is the result of current commit (88ae5ee) vs. master branch. A few of them (`access_all` and `fill_A!`) are slightly faster, some are comparable (`convert_asciistring`, `each_3mer_step1`, `each_3mer_step3`), and others are tremendously slower. This would be because I removed some complicated algorithms that are not directly applicable to the new sequence representation, so I'm going to revise them.

benchseq

**Comment by Ward9250** [comment]
Can they be used but just for the given sequence type to which they apply? I would have thought performance of the 2-bit encoding wouldn't change much.

**Comment by Ward9250** [comment]
The macro for helping people create alphabets works for me on my machine now #136 - tests still fail, but it's the same tests as fail for this PR. I think this is going to be great. If we can come up with a simple and standard way for people to create sets of characters, and then an alphabet. We can say, ok for your alphabet you can expect BioSequence{*your alphabet*} to do *list of things here - get, set, indexing, match/mismatch etc* in an efficient manner.

**Comment by bicycle1885** [comment]
> Can they be used but just for the given sequence type to which they apply?

Yes, but now I don't run any test for 2-bit sequences and there may be silly bugs. I'll try it later.

**Comment by bicycle1885** [comment]
> The macro for helping people create alphabets works for me on my machine now #136

It looks cool! I'll check it once this pull request settles down.

Here is the progress of performance improvement:

benchseq

**Comment by bicycle1885** [comment]
OK, now I removed most of performance regressions:

benchseq


I guess 2x slow downs of `count_nucs` and `make_complement` would be almost inevitable because we are handling more types of nucleotides in 4-bit encoding of DNA.

**Comment by Ward9250** [comment]
I think that is fair to expect, more nucleotides, more bits, more time. If
people want faster counting they can use 2-bit encoding. This is really
fantastic stuff.

On Sun, Mar 6, 2016 at 2:15 PM, Kenta Sato (佐藤 建太) <notifications@github.com

**Comment by bicycle1885** [comment]
Thank you :). 
This pull request wil solve #18, #132, #134 in one shot.

I will add more tests for 2-bit sequences and make examples like gaps and stop codons to https://github.com/BioJulia/BioFmtSpecimens.

**Comment by bicycle1885** [comment]
I've added many operations addressed in #129: `resize!`, `push!`, `pop!`, `shift!`, `unshift!`, `append`, `insert!` and `deleteat!` for `BioSequence`. Now sequences behave more like vectors.

Further, I've found that removing mutable/immutable state of sequences simplifies stuff without losing performance. `seq[i:j]` always creates a lightweight view of `seq`. Copying underlying data happens only when we try to modify a sequence whose data are shared with other sequences. This is something like a [copy-on-write](https://en.wikipedia.org/wiki/Copy-on-write) strategy and it is used when [forking a child process in Linux Kernel](http://linux.die.net/man/2/fork).

**Comment by Ward9250** [comment]
Copy on write is also the mechanism at work in R. It works well unless you
want to modify something many many times, in which case it sucks, but our
seq types are different, because it's only copy on write when data is
shared. I like this!

On Tue, Mar 8, 2016 at 6:52 PM, Kenta Sato (佐藤 建太) <notifications@github.com

**Comment by bicycle1885** [comment]
I've added the [MurmurHash3](https://en.wikipedia.org/wiki/MurmurHash)-like function. Though written in pure Julia, this is as fast as builtin the `hash` function of Base (written in C) for enough long sequence (benchmark script is here: https://gist.github.com/bicycle1885/78a5fb65dea6b3ac4a4d):

```
~/.j/v/Bio (newseq|✚3…) $ julia benchhash.jl
ASCIIString
  0.000765 seconds
  0.000923 seconds
  0.000936 seconds

DNASequence (aligned)
  0.000493 seconds
  0.000468 seconds
  0.000497 seconds

DNASequence (unaligned)
  0.000941 seconds
  0.000960 seconds
  0.000913 seconds
```

This enables to create dictionaries whose keys are our sequences.

Now I've finished to implement functionality I wanted in the new sequence type, so I'll start to clean up the commits.

**Comment by bicycle1885** [comment]
OK, this is ready to be reviewed.

**Comment by Ward9250** [comment]
That's awesome, I approve. Let me know what you think of #136 and whether it's ok to add into this.

**Comment by bicycle1885** [comment]
I'd like to add a few more commits here.

**Comment by kescobo** [comment]
Just skimming comments, and all of it sounds great. I'm not sure if there's policy on this, but should there be a requirement to update the docs when a major change like this occurs before merging? Seems like it could cause a lot of confusion if the docs lag too far behind alterations to core functionality.

**Comment by bicycle1885** [comment]
Yes, documentation should come with this major change. One obstacle against writing docs in Julia is there is no definitive documentation system. I think we should select one as soon as possible. Judo.jl, which is used to generate [our current document](http://biojulia.github.io/Bio.jl/), is not maintained and I've failed to use it when I tried last time. The most promising one I think is [Lapidary.jl](https://github.com/MichaelHatherly/Lapidary.jl), but it's still under active development. You can view its self-hosted document here: http://michaelhatherly.github.io/Lapidary.jl/latest/. cc: @Ward9250 @Blahah

**Comment by Ward9250** [comment]
Judo.jl is not maintained? I thought this was @dcjones package? To be clear, Julia does have an inbuilt system for documenting API's, types and methods, just not one for generating docs sites or PDFs and that kind thing a'la R's PDF/HTML documentation and vignettes via ROxygen.

**Comment by Ward9250** [comment]
#139

**Comment by Ward9250** [comment]
We have a Lapidary.jl system working now with travis.ci automatic building and hosting on gh-pages through mkdocs :) So that works, it's just a case of updating the documentation.

**Comment by bicycle1885** [comment]
I've added docs about new sequence data structure and extended symbols. We still need to brush up descriptions and styles, but it's not so urgent.

**Comment by Ward9250** [comment]
So long as it is documented, we can brush up documentation and make it consistent later.

**Comment by Ward9250** [comment]
Are there any more commits to come?

**Comment by bicycle1885** [comment]
No. Let's merge it!

**Pull request merged**
