### PR TITLE
WIP: Optimization/Bugfix Omnibus

### PR DESCRIPTION
**Pull request by dcjones**
I'm rushing to put together my talk for JuliaCon next week. In the process I'm optimizing and fixing things I encounter. Though ideally I would make a separate PRs for each of these changes, I'm in a hurry so I'm just going to push changes as I make them to this PR and merge sometime before my talk on Thursday.

None of these should be breaking changes, only optimizing, fixing, and adding minor features.

Changes so far:
  * Fix a out of bounds exception in parsing that I somehow never encountered before.
  * Significant optimizations to nucleotide and k-mer iterators.
  * Add an option to `translate` to turn ambiguous codons into `X` rather than throwing at error.
  * Add `KmerCounts` that works analogously to `NucleotideCounts`.

### CODE REVIEW

**Comment by Ward9250** [comment]
Ah yes I recall that using @inline was recommended for iteration methods by Tim Holy on a PR on the Julia repo once - making sure to avoid the cost of the function calls.

**Comment by dcjones** [comment]
It was a big boon to kmer and nucleotide iterator speed, maybe not surprisingly since those can involve calling the same relatively simple function hundreds of millions of times. We're faster than SeqAn and Biostrings with a lot of basic sequence operations now.

**Comment by Ward9250** [comment]
When you're done with the JuliaCon talk will you upload it? I'd love to see it!

**Comment by dcjones** [comment]
I'll put it up in github repo this weekend in an incomplete state so people can comment. I'd be happy to get feedback on it, or suggestions for things to add.

**Comment by bicycle1885** [comment]
Great work! Though I cannot fully check the code, it looks well-tested. I think it's okay to merge it.

**Comment by dcjones** [comment]
This fails tests, but only because I need to tag a new version of IntervalTrees. I'm going to go ahead and merge.

**Pull request merged**
