### PR TITLE
Documentation for Bio.Structure

### PR DESCRIPTION
**Pull request by jgreener64**
Hi all,

This PR adds documentation for `Bio.Structure` in the Lapidary.jl format. It also expands a few in-code docs.

Let me know if it looks okay. Thanks,
Joe

### CODE REVIEW

**Comment by bicycle1885** [comment]
Great @jgreener64! Just skimmed it, LGTM.

**Comment by Ward9250** [comment]
The doc builder is failing for some reason in the Travis Build Log.

**Comment by jgreener64** [comment]
Ah, yes.
As part of the doc tests I download a PDB file, which runs the `download` Julia function. This seems to have problems with the autobuild.
Any suggestions here, e.g. could the docs access the `BioFmtSpecimens` in any way? Or I could store one file somewhere in the docs directory?

**Comment by bicycle1885** [comment]
Hmm, I'm not sure but this may be due to a resource leak of opened files in Lapidary.jl (it has been renamed to Documenter.jl) since the error message says:
```
ERROR: LoadError: could not spawn `which curl`: too many open files (EMFILE)
```

**Comment by jgreener64** [comment]
I removed the doc tests to see if it fixed the error. The `LoadError` above goes but there still seem to be some doc build problems.

**Comment by Ward9250** [comment]
Actually it looks ok according to the travis log. The reason the docs look like they build fine, but they skip deployment. This behaviour is intended, as only builds on master deploy docs - Because docs deployment directly manipulates the a folder subtree of the gh-pages Branch, and we only want docs online of content that's actually in master or a release.

**Comment by jgreener64** [comment]
Ah yeah makes sense.
In that case this is ready for review I think.

**Comment by Ward9250** [comment]
Do you think it's possible to include the file that is downloaded in the package or better yet in BioFmtSpecimens? We have tests which access BioFmtSpecimens so if you add the files you want to BioFmtSpecimens we can take a look at getting it to use them and see if it works :).

**Comment by jgreener64** [comment]
Yeah that would be ideal - the file is already in `BioFmtSpecimens` as it happens at `PDB/1EN2.pdb`.

I guess, similar to in the tests, I would run `get_bio_fmt_specimens()` during setup then access a file using `Pkg.dir("Bio", "test", "BioFmtSpecimens", "PDB", "1EN2.pdb")`?

I will attempt this now.

**Comment by jgreener64** [comment]
Have attempted with `BioFmtSpecimens`. Let's see how the build goes.

**Comment by Ward9250** [comment]
Hey, this looks like it worked! :tada:

**Comment by Ward9250** [comment]
I'm happy to merge this. There's currently no struct guidelines for the manual pages. API docstrings are covered in the code guidelines. Maybe we'll make manual guidelines in the near future, but this looks good! :+1:

**Comment by jgreener64** [comment]
:tada: Yeah seemed to work! Great, thanks.

**Comment by Ward9250** [comment]
Now it has merged, we'll be able to see if biojulia.github.io/Bio.jl/latest/ gets updated in about 15 minutes!

**Comment by Ward9250** [comment]
It's up! :tada:

**Pull request merged**
