### PR TITLE
add Base.findnext for BioSequence

### PR DESCRIPTION
**Pull request by bicycle1885**
This adds the `findnext` method.

### CODE REVIEW

**Comment by Ward9250** [comment]
Nice! When it's RTR shall we give Omniref a try with this PR?

**Comment by bicycle1885** [comment]
Of course :+1:

**Comment by Ward9250** [comment]
Interesting, Omniref isn't working for me. It thinks the commit info has been garbage collected by git.

**Comment by Ward9250** [comment]
I've filled a bug report with Omniref.

**Comment by bicycle1885** [comment]
I added more methods that have the `find` prefix, namely `findnext`, `findprev`, `findfirst`, and `findlast`. @Ward9250 Did you get a feedback from Omniref?

**Comment by Ward9250** [comment]
I did, they resynced stuff, fixed the bug and apologised.

**Comment by bicycle1885** [comment]
So, please try it if you want. I don't hurry, but some branches on my local machine depend on this pull request.

**Pull request merged**
