### PR TITLE
add documentation for blast module

### PR DESCRIPTION
**Pull request by kescobo**
Documentation for the blast command line wrapper. Please let me know if I should add anything else.

### CODE REVIEW

**Comment by Ward9250** [comment]
This LGTM 👍 the modules make sense. Looks like some nice simple examples! I'm happy to merge this. On merge it should update the web - although the build can take some minutes.

**Comment by jgreener64** [comment]
Looks good! Am I missing something, or have the online docs not been updated?
Does `mkdocs.yml` need to be updated?

**Comment by Ward9250** [comment]
The docs build system won't kick in unless tests pass on julia v0.4. Because there's no point in building documentation for things that don't work as expected and adding a whole ton of commits to the gh-pages while people are tinkering or developing. That's the current settings anyway. The idea being when we make tagged releases, they will have a successful build and passing test suite, and so the website will have a "latest" docs which will be docs of the last time the in development stuff passed it's tests, then docs for v0.0.1, v0.5 and so on. #159 is the current sticking point here that's stopping the docs build system from generating the pages for blast.

**Comment by jgreener64** [comment]
Ah okay that makes sense :+1:

**Pull request merged**
