### PR TITLE
Writer interfaces for FASTA and FASTQ file formats.

### PR DESCRIPTION
**Pull request by bicycle1885**
This implements writers for FASTA and FASTQ (ref: #208).

### CODE REVIEW

**Comment by Ward9250** [comment]
This looks really fantastic, can't wait to use it on my FASTA sequences!

**Comment by bicycle1885** [comment]
Okay, it's almost ready to merge. Let's wait for the results of CI.

**Comment by bicycle1885** [comment]
Ah, I need to write docs. But theoretically it can be a separated pull request.

**Comment by Ward9250** [comment]
LGTM :+1:

**Pull request merged**
